// File generated by flutterfire configure for project ecommerce-danhil

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfsLzezpN0WpioMCvpDJI70NQLJ-xxVZY',
    appId: '1:909899520469:web:1ee121c94eb7b43eb4455c',
    messagingSenderId: '909899520469',
    projectId: 'ecommerce-danhil',
    authDomain: 'ecommerce-danhil.firebaseapp.com',
    storageBucket: 'ecommerce-danhil.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfsLzezpN0WpioMCvpDJI70NQLJ-xxVZY',
    appId: '1:909899520469:android:1ee121c94eb7b43eb4455c',
    messagingSenderId: '909899520469',
    projectId: 'ecommerce-danhil',
    storageBucket: 'ecommerce-danhil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfsLzezpN0WpioMCvpDJI70NQLJ-xxVZY',
    appId: '1:909899520469:ios:1ee121c94eb7b43eb4455c',
    messagingSenderId: '909899520469',
    projectId: 'ecommerce-danhil',
    storageBucket: 'ecommerce-danhil.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce_app',
  );
}
